### ISSUE TITLE
Crash on streaming radio

### ISSUE THREAD

**Issue by Pe8er** [tomodwyer/airsonos#1]
Hi there!

First of all - thank you so much for picking up this project! Such a great utility. I have a bit of an issue though: when streaming radio from [this app](https://itunes.apple.com/us/app/polskie-radio/id441743093?mt=8), Airsonos consistently crashes. Here's the error log:

```
Searching for Sonos devices on network...

Kitchen (@ 192.168.1.6:1400, RINCON_949F3E14C63601400:2455140802)

Search complete. Set up 1 device tunnel.
/home/pi/airsonos/node_modules/nodetunes/lib/rtspmethods.js:254
        req.content.toString().trim()
                   ^

TypeError: Cannot read property 'toString' of undefined
    at setParameter (/home/pi/airsonos/node_modules/nodetunes/lib/rtspmethods.js:254:20)
    at ServerParser.parser.on (/home/pi/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:125:13)
    at ServerParser.emit (events.js:213:7)
    at ServerParser._emitMessage (/home/pi/airsonos/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/home/pi/airsonos/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at ServerParser.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

Raspberry Pi 3 on Raspbian GNU/Linux 8 (jessie)
node v8.5.0
npm v5.3.0

Thanks for looking into it!

**Comment by tomodwyer** [comment]
Hi @Pe8er - I've tracked it down to the artwork sent along wth the Polskie Radio app has a `Content-Type` that wasn't accounted for (`"image/none"`).

I will update the [nodetunes repo](https://github.com/tomodwyer/nodetunes) and send you a link to test shortly

**Comment by tomodwyer** [comment]
@Pe8er - if you go into your [`package.json`](https://github.com/tomodwyer/airsonos/blob/master/package.json) file and change [line 39](https://github.com/tomodwyer/airsonos/blob/master/package.json#L39) to:

```json
    "nodetunes": "git://github.com/tomodwyer/nodetunes.git#content-type",
```

Then from the command line, go to your airsonos project folder and run:  
`rm -rf node_modules && npm install && npm start`

and let me know if that works?

**Comment by Pe8er** [comment]
Thank you for quick reply! I won't be near my Sonos until Monday, I will check it then.
