### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Sc4nd4l** [tomodwyer/airsonos#12]
Using Rasperry Pi with rasbian. 

`Searching for Sonos devices on network...

/home/pi/airsonos/node_modules/sonos/lib/logicalDevice.js:84
        devices.forEach(function(device) {
                ^

TypeError: Cannot read property 'forEach' of null
    at /home/pi/airsonos/node_modules/sonos/lib/logicalDevice.js:84:17
    at /home/pi/airsonos/node_modules/sonos/lib/sonos.js:719:7
    at Parser.<anonymous> (/home/pi/airsonos/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:182:13)
    at SAXParser.saxParser.onclosetag (/home/pi/airsonos/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/home/pi/airsonos/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/pi/airsonos/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/home/pi/airsonos/node_modules/sax/lib/sax.js:861:5)
    at SAXParser.write (/home/pi/airsonos/node_modules/sax/lib/sax.js:1293:29)
    at Parser.exports.Parser.Parser.parseString (/home/pi/airsonos/node_modules/xml2js/lib/xml2js.js:273:29)
    at Parser.parseString (/home/pi/airsonos/node_modules/xml2js/lib/xml2js.js:6:61)
    at Object.exports.parseString (/home/pi/airsonos/node_modules/xml2js/lib/xml2js.js:296:19)
    at Request._callback (/home/pi/airsonos/node_modules/sonos/lib/sonos.js:702:12)
    at Request.self.callback (/home/pi/airsonos/node_modules/request/request.js:129:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/pi/airsonos/node_modules/request/request.js:873:14)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/home/pi/airsonos/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by tomodwyer** [comment]
I think this is a problem with the [node-sonos](https://github.com/bencevans/node-sonos/issues/344) package - I'll look for an update.

**Comment by svrooij** [comment]
The version of node-sonos you’re using is [some fork](
https://github.com/npwalker/node-sonos), that is 4 years old..... so you’re right that their is a problem but not something we can fix. Would be nice if the changes in the fork of node-sonos would be merged to the ‘official’ version. But after checking that would require a massive time investment. In January 2018 the npm version of [node-sonos](https://github.com/bencevans/node-sonos) is completely rewritten to be fully async and have a decent event system.

Here is the issue that might steer you in the right direction, about the current issue.

https://github.com/bencevans/node-sonos/issues/332

**Comment by Kongledyret** [comment]
Seems like they have resolved it in the issue mentioned here

**Comment by Kongledyret** [comment]
I can debug for you if needed

**Comment by tomodwyer** [comment]
> I can debug for you if needed

Happy for you to pick this up if you think you can resolve it.

**Comment by svrooij** [comment]
The used fork created some kind of logical device, that is something that doesn’t exists in the current node-sonos library. By my knowledge it creates a device for each current group.

But we do have a decent event listener so that part could be greatly improved... anyone interested to fix this in the true node-sonos library?

**Comment by vrspider** [comment]
Had the same issue on my mac, I am using the player 3.

**Comment by italianbloke** [comment]
Something pretty similar on my mac as well, any advise welcome:

yarn start
yarn run v1.10.1
$ babel-node ./lib/index.js
Searching for Sonos devices on network...

/usr/local/share/man/man1/airsonos/node_modules/sonos/lib/logicalDevice.js:84
        devices.forEach(function(device) {
                ^

TypeError: Cannot read property 'forEach' of null
    at /usr/local/share/man/man1/airsonos/node_modules/sonos/lib/logicalDevice.js:84:17
    at /usr/local/share/man/man1/airsonos/node_modules/sonos/lib/sonos.js:719:7
    at Parser.<anonymous> (/usr/local/share/man/man1/airsonos/node_modules/xml2js/lib/xml2js.js:255:20)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at SAXParser.saxParser.onclosetag (/usr/local/share/man/man1/airsonos/node_modules/xml2js/lib/xml2js.js:225:24)
    at emit (/usr/local/share/man/man1/airsonos/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/share/man/man1/airsonos/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/share/man/man1/airsonos/node_modules/sax/lib/sax.js:861:5)
    at SAXParser.write (/usr/local/share/man/man1/airsonos/node_modules/sax/lib/sax.js:1293:29)
    at Parser.exports.Parser.Parser.parseString (/usr/local/share/man/man1/airsonos/node_modules/xml2js/lib/xml2js.js:273:29)
    at Parser.parseString (/usr/local/share/man/man1/airsonos/node_modules/xml2js/lib/xml2js.js:6:61)
    at Object.exports.parseString (/usr/local/share/man/man1/airsonos/node_modules/xml2js/lib/xml2js.js:296:19)
    at Request._callback (/usr/local/share/man/man1/airsonos/node_modules/sonos/lib/sonos.js:702:12)
    at Request.self.callback (/usr/local/share/man/man1/airsonos/node_modules/request/request.js:129:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/usr/local/share/man/man1/airsonos/node_modules/request/request.js:873:14)
    at Request.emit (events.js:187:15)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/usr/local/share/man/man1/airsonos/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:187:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
